Repository linode/linode-cli, pull requests merged in 2024-03, with the labels that each got.

#586 doc: Add development guide to wiki
  Makefile
  linodecli/configuration/auth.py
  wiki/Home.md
  wiki/OpenAPI Extensions.md
  wiki/_Sidebar.md
  wiki/development/Development - Index.md
  wiki/development/Development - Overview.md
  wiki/development/Development - Setup.md
  wiki/development/Development - Skeleton.md
  wiki/development/Development - Testing.md
Labels: documentation

#585 new: Improve generated command help page formatting using Rich
  linodecli/__init__.py
  linodecli/arg_helpers.py
  linodecli/baked/request.py
  linodecli/help_pages.py
  linodecli/helpers.py
  tests/unit/test_arg_helpers.py
  tests/unit/test_help_pages.py
  tests/unit/test_helpers.py
Labels: documentation, improvement, new-feature

#588 fix: Resolve help page error for list commands with non-standard names
  linodecli/help_pages.py
  tests/integration/domains/test_domain_records.py
Labels: bugfix

#590 doc: Clarify how list argument differentiates objects
  wiki/Usage.md
Labels: documentation
