Repository linode/linode-cli, pull requests merged in 2024-12, with the labels that each got.

#684 test: Add LKE ACL cases
  tests/integration/helpers.py
  tests/integration/lke/test_clusters.py
  tests/integration/lke/test_lke_acl.py
Labels: testing

#696 Integration test
  tests/integration/account/test_account.py
  tests/integration/linodes/test_configs.py
  tests/integration/linodes/test_disk.py
  tests/integration/lke/test_clusters.py
  tests/integration/users/test_profile.py
Labels: testing

#694 Response bodies included in debug output
  linodecli/api_request.py
  tests/unit/test_api_request.py
Labels: improvement

#697 Support dictionary values in API responses
  linodecli/baked/response.py
  tests/fixtures/response_test_get.yaml
  tests/unit/test_response.py
Labels: bugfix

#695 Only use +and in filters when necessary
  linodecli/api_request.py
  tests/unit/test_api_request.py
Labels: bugfix

#701 Support oneOfs & anyOfs in operation request & response schema
  linodecli/baked/operation.py
  linodecli/baked/request.py
  linodecli/baked/response.py
  linodecli/baked/util.py
  linodecli/help_pages.py
  tests/fixtures/operation_with_one_ofs.yaml
  tests/unit/conftest.py
  tests/unit/test_help_pages.py
  tests/unit/test_request.py
  tests/unit/test_response.py
Labels: new-feature
