Repository linode/linode-cli, pull requests merged in 2024-04, with the labels that each got.

#598 ref: Improve maintainability of `colors.py`
  linodecli/baked/colors.py
Labels: improvement

#599 ref: Refactor `plugins/__init__.py` for maintainability
  linodecli/arg_helpers.py
  linodecli/plugins/__init__.py
  linodecli/plugins/plugins.py
  tests/unit/test_arg_helpers.py
  wiki/development/Development - Skeleton.md
Labels: improvement

#601 ref: Refactor `baked/operation.py`
  linodecli/baked/operation.py
Labels: improvement

#602 ref: Move build configuration from `setup.py` to `pyproject.toml`; apply various repo/CI refactors
  .github/ISSUE_TEMPLATE/bug.yml
  .github/workflows/e2e-suite-pr.yml
  .github/workflows/e2e-suite.yml
  .github/workflows/nightly-smoke-tests.yml
  .github/workflows/publish-oci.yml
  .github/workflows/pull-request.yml
  .github/workflows/unit-tests.yml
  Dockerfile
  Jenkinsfile
  MANIFEST.in
  Makefile
  linodecli/__init__.py
  linodecli/arg_helpers.py
  linodecli/completion.py
  linodecli/version.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.py
  tests/unit/test_arg_helpers.py
  tests/unit/test_completion.py
  wiki/Installation.md
  wiki/development/Development - Setup.md
Labels: repo-ci-improvement

#603 new: update pyenv to use environment name
  .python-version
Labels: repo-ci-improvement

#593 Add test integration
  tests/integration/account/test_account.py
  tests/integration/beta/test_beta_program.py
  tests/integration/database/test_database.py
  tests/integration/helpers.py
  tests/integration/lke/test_clusters.py
  tests/integration/longview/test_longview.py
  tests/integration/managed/test_managed.py
  tests/integration/obj/test_obj_bucket.py
  tests/integration/regions/test_plugin_region_table.py
Labels: testing
