Repository linode/linode-cli, pull requests merged in 2024-10, with the labels that each got.

#649 test: Fix slack payload in integration workflow
  .github/workflows/e2e-suite.yml
Labels: testing

#653 Override images replicate output
  linodecli/overrides.py
Labels: improvement

#648 fix: get-kubeconfig merge into empty lists
  linodecli/plugins/get-kubeconfig.py
  tests/unit/test_plugin_kubeconfig.py
Labels: bugfix

#652 new: Allow specifying a custom configuration path through environment variable
  linodecli/configuration/config.py
  linodecli/configuration/helpers.py
  linodecli/help_pages.py
  tests/unit/test_configuration.py
  wiki/Configuration.md
  wiki/development/Development - Overview.md
Labels: new-feature

#658 Sanitize Bearer Token in debug output
  linodecli/api_request.py
  tests/unit/test_api_request.py
Labels: improvement

#644 send errors and warnings to stderr
  linodecli/__init__.py
  linodecli/arg_helpers.py
  linodecli/cli.py
  linodecli/configuration/auth.py
  linodecli/configuration/config.py
  linodecli/plugins/firewall-editor.py
  linodecli/plugins/image-upload.py
  linodecli/plugins/obj/__init__.py
  linodecli/plugins/obj/helpers.py
  linodecli/plugins/obj/list.py
  linodecli/plugins/plugins.py
  linodecli/plugins/region-table.py
  linodecli/plugins/regionstats.py.example
  linodecli/plugins/ssh.py
Labels: breaking-change, improvement

#629 new: Add support for loading JSON OpenAPI spec files
  .github/workflows/docker-build.yml
  Dockerfile
  Makefile
  linodecli/__init__.py
  linodecli/arg_helpers.py
  linodecli/baked/parsing.py
  linodecli/cli.py
  tests/fixtures/cli_test_load.json
  tests/fixtures/cli_test_load.yaml
  tests/unit/conftest.py
  tests/unit/test_arg_helpers.py
  tests/unit/test_cli.py
Labels: new-feature

#665 CI: Notify slack channel on releases; Add test coverage for vlans and lke types
  .github/workflows/release-notify-slack.yml
  tests/integration/linodes/test_power_status.py
  tests/integration/lke/test_clusters.py
  tests/integration/vlans/test_vlans.py
Labels: repo-ci-improvement

#668 test: fix unit tests caused by error output being routed to stderr instead of stdout
  Makefile
  tests/unit/test_configuration.py
  tests/unit/test_plugin_image_upload.py
  tests/unit/test_plugin_ssh.py
Labels: testing
