Repository linode/linode-cli, pull requests merged in 2024-05, with the labels that each got.

#604 Improve the readability of CLI help page and table outputs
  linodecli/__init__.py
  linodecli/baked/colors.py
  linodecli/baked/response.py
  linodecli/help_pages.py
  linodecli/output.py
  linodecli/overrides.py
  linodecli/plugins/obj/__init__.py
  linodecli/plugins/obj/helpers.py
  tests/unit/test_help_pages.py
  tests/unit/test_output.py
  tests/unit/test_response.py
  wiki/development/Development - Overview.md
Labels: improvement

#612 CI: replace test execution handler with conditional
  .github/workflows/e2e-suite.yml
  Makefile
Labels: testing, repo-ci-improvement

#605 integration tests
  tests/integration/conftest.py
  tests/integration/support/test_support.py
  tests/integration/users/test_profile.py
Labels: testing

#614 test: Add skip for backup test for managed test accounts
  tests/integration/cli/test_host_overrides.py
  tests/integration/linodes/test_backups.py
Labels: testing

#617 fix: Resolve cell rendering error in OBJ plugin
  linodecli/plugins/obj/helpers.py
Labels: bugfix
