Repository linode/linode-cli, pull requests merged in 2024-11, with the labels that each got.

#662 Fix issue displaying missing action errors when `--help` is specified
  linodecli/__init__.py
  linodecli/cli.py
  linodecli/exit_codes.py
  linodecli/help_pages.py
  tests/unit/test_cli.py
  tests/unit/test_help_pages.py
Labels: bugfix

#678 Account for edge case where apiVersion param has no default
  linodecli/baked/operation.py
  tests/fixtures/api_url_components_test.yaml
  tests/unit/test_operation.py
Labels: bugfix

#676 test: Improve flaky reboot instance test; Implement retry for execute test command function
  tests/integration/helpers.py
  tests/integration/linodes/test_power_status.py
Labels: testing

#674 test: Allow integration and unit tests to run against EOL or desired python version
  .github/workflows/e2e-suite.yml
  .github/workflows/unit-tests.yml
Labels: testing

#680 Improve parsing & formatting of help page descriptions
  linodecli/baked/operation.py
  linodecli/baked/parsing.py
  linodecli/baked/request.py
  tests/unit/test_parsing.py
Labels: improvement

#681 Exclude parameter values from API request bodies
  linodecli/api_request.py
  linodecli/baked/operation.py
  tests/fixtures/api_request_test_foobar_put.yaml
  tests/integration/cli/test_help.py
  tests/unit/conftest.py
  tests/unit/test_api_request.py
Labels: bugfix

#677 test: Add test coverage for Disk Encryption, Config, and Disk
  .github/workflows/e2e-suite-windows.yml
  .github/workflows/e2e-suite.yml
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/linodes/helpers_linodes.py
  tests/integration/linodes/test_backups.py
  tests/integration/linodes/test_configs.py
  tests/integration/linodes/test_disk.py
  tests/integration/linodes/test_linodes.py
  tests/integration/linodes/test_power_status.py
  tests/integration/linodes/test_rebuild.py
  tests/integration/linodes/test_resize.py
  tests/integration/linodes/test_types.py
  tests/integration/lke/test_clusters.py
  tests/integration/managed/test_managed.py
  tests/integration/obj/test_obj_bucket.py
  tests/integration/placements/test_placements.py
  tests/integration/vpc/conftest.py
  tests/integration/vpc/test_vpc.py
Labels: testing

#682 test: Update SSH and VLAN test cases
  tests/integration/linodes/test_disk.py
  tests/integration/ssh/test_plugin_ssh.py
  tests/integration/vlans/test_vlans.py
Labels: testing

#683 Release v5.55.0
  .github/dependabot.yml
  .github/workflows/e2e-suite-windows.yml
  .github/workflows/e2e-suite.yml
  .github/workflows/labeler.yml
  .github/workflows/publish-oci.yml
  .github/workflows/remote-release-trigger.yml
  .github/workflows/unit-tests.yml
  Makefile
  linodecli/__init__.py
  linodecli/api_request.py
  linodecli/baked/operation.py
  linodecli/baked/parsing.py
  linodecli/baked/request.py
  linodecli/cli.py
  linodecli/exit_codes.py
  linodecli/help_pages.py
  linodecli/overrides.py
  tests/fixtures/api_request_test_foobar_put.yaml
  tests/fixtures/api_url_components_test.yaml
  tests/integration/cli/test_help.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/linodes/helpers_linodes.py
  tests/integration/linodes/test_backups.py
  tests/integration/linodes/test_configs.py
  tests/integration/linodes/test_disk.py
  tests/integration/linodes/test_linodes.py
  tests/integration/linodes/test_power_status.py
  tests/integration/linodes/test_rebuild.py
  tests/integration/linodes/test_resize.py
  tests/integration/linodes/test_types.py
  tests/integration/lke/test_clusters.py
  tests/integration/managed/test_managed.py
  tests/integration/obj/test_obj_bucket.py
  tests/integration/placements/test_placements.py
  tests/integration/ssh/test_plugin_ssh.py
  tests/integration/vlans/test_vlans.py
  tests/integration/vpc/conftest.py
  tests/integration/vpc/test_vpc.py
  tests/unit/conftest.py
  tests/unit/test_api_request.py
  tests/unit/test_cli.py
  tests/unit/test_configuration.py
  tests/unit/test_help_pages.py
  tests/unit/test_operation.py
  tests/unit/test_parsing.py
  tests/unit/test_plugin_image_upload.py
  tests/unit/test_plugin_ssh.py
Labels: ignore-for-release
