Repository linode/linode-cli, pull requests merged in 2024-09, with the labels that each got.

#635 Add suppress-version-warning config option
  linodecli/api_request.py
  linodecli/configuration/config.py
  tests/unit/test_configuration.py
  wiki/Configuration.md
Labels: new-feature

#638 new: Break out command help page logic; sort actions in output
  linodecli/__init__.py
  linodecli/help_pages.py
  tests/unit/conftest.py
  tests/unit/test_help_pages.py
Labels: improvement

#646 test: Update volume tests to reflect new threshold values for sizing
  tests/integration/volumes/test_volumes.py
  tests/integration/volumes/test_volumes_resize.py
Labels: testing

#647 test: Add retry on flaky tests
  pyproject.toml
  tests/integration/linodes/test_power_status.py
  tests/integration/linodes/test_rebuild.py
  tests/integration/linodes/test_resize.py
  tests/integration/lke/test_clusters.py
Labels: testing
