Repository linode/linode-cli, pull requests merged in 2025-05, with the labels that each got.

#768 Unskip LKE enterprise tier related tests
  tests/integration/lke/test_lke_enterprise.py
Labels: testing

#761 Allow specifying explicitly empty dicts and lists for object arguments
  linodecli/api_request.py
  linodecli/baked/operation.py
  tests/integration/lke/test_clusters.py
  tests/unit/test_api_request.py
  tests/unit/test_operation.py
Labels: bugfix, new-feature

#771 Update disk encryption node pool test
  tests/integration/lke/test_clusters.py
Labels: testing

#770 Release v5.57.1
  .github/workflows/release.yml
  .github/workflows/remote-release-trigger.yml
  linodecli/api_request.py
  linodecli/baked/operation.py
  tests/integration/lke/test_clusters.py
  tests/integration/lke/test_lke_enterprise.py
  tests/unit/test_api_request.py
  tests/unit/test_operation.py
Labels: ignore-for-release

#772 Add lke versions helper and update tests
  tests/integration/lke/test_lke_enterprise.py
Labels: testing

#774 Add and update test coverage for spec v4.199.0
  tests/integration/cli/test_help.py
  tests/integration/firewalls/test_firewalls.py
  tests/integration/firewalls/test_firewalls_rules.py
  tests/integration/helpers.py
  tests/integration/linodes/helpers_linodes.py
  tests/integration/linodes/test_interfaces.py
  tests/integration/linodes/test_linode_interfaces.py
  tests/integration/nodebalancers/test_node_balancers.py
  tests/integration/obj/test_obj_quota.py
  tests/integration/volumes/test_volumes.py
Labels: testing

#776 Added override for DB Engine Config view commands
  linodecli/overrides.py
Labels: improvement
