Repository linode/linode-cli, pull requests merged in 2025-01, with the labels that each got.

#705 Multiple workflow changes
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/docker-build.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/pull-request.yml
  .github/workflows/release-notify-slack.yml
  .github/workflows/release.yml
  Makefile
Labels: repo-ci-improvement

#718 Address incompatibility between boto3 >= 1.36.x and third-party S3-compatible storage providers
  linodecli/plugins/obj/__init__.py
  tests/integration/conftest.py
  tests/integration/image/test_plugin_image_upload.py
Labels: bugfix

#717 Release v5.56.1
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/docker-build.yml
  .github/workflows/e2e-suite-windows.yml
  .github/workflows/e2e-suite.yml
  .github/workflows/nightly-smoke-tests.yml
  .github/workflows/publish-pypi.yml
  .github/workflows/pull-request.yml
  .github/workflows/release-notify-slack.yml
  .github/workflows/release.yml
  .github/workflows/remote-release-trigger.yml
  Makefile
  linodecli/configuration/config.py
  linodecli/plugins/obj/__init__.py
  tests/integration/conftest.py
  tests/integration/image/test_plugin_image_upload.py
Labels: ignore-for-release
