Repository linode/linode-cli, pull requests merged in 2025-04, with the labels that each got.

#750 Add object-storage integration tests
  tests/integration/obj/conftest.py
  tests/integration/obj/test_obj_bucket.py
  tests/integration/obj/test_obj_plugin.py
  tests/integration/obj/test_object_storage.py
Labels: testing

#757 Error on missing x-linode-cli-command extension; log when operationId is used for action
  linodecli/cli.py
  tests/fixtures/cli_test_bake_missing_cmd_ext.yaml
  tests/unit/test_cli.py
Labels: improvement

#758 Add LKE tier integration tests
  tests/integration/lke/test_clusters.py
  tests/integration/lke/test_lke_enterprise.py
Labels: testing, do-not-merge

#764 Fixed domain test failures caused by `--target-command` argument
  linodecli/__init__.py
  linodecli/arg_helpers.py
Labels: bugfix

#763 Trusted publisher for PyPI
  .github/workflows/release.yml
Labels: repo-ci-improvement
