Repository linode/linode-cli, pull requests merged in 2025-02, with the labels that each got.

#727 Consume linode-api-docs/openapi.json rather than openapi.yaml
  resolve_spec_url
Labels: repo-ci-improvement

#728 Release v5.56.2
  .github/workflows/release.yml
  .github/workflows/remote-release-trigger.yml
  linodecli/configuration/helpers.py
  pyproject.toml
  resolve_spec_url
  tests/unit/test_configuration.py
Labels: ignore-for-release

#729 ref: Improve maintainability for baked request and response
  linodecli/baked/request.py
  linodecli/baked/response.py
Labels: improvement

#726 Add fallback value to replace explicitly option checking for config gets
  linodecli/configuration/config.py
  linodecli/configuration/helpers.py
Labels: improvement

#733 Add Uninstall Document
  wiki/Uninstallation.md
  wiki/_Sidebar.md
Labels: documentation
